# Generated by Django 2.1 on 2021-02-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=32)),
                ('kh', models.CharField(max_length=32)),
                ('km', models.CharField(max_length=32)),
                ('xf', models.IntegerField()),
                ('xs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('yxh', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('yxm', models.CharField(max_length=32)),
                ('lxdh', models.CharField(max_length=32, unique=True)),
                ('dz', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xn', models.CharField(max_length=32)),
                ('xq', models.CharField(max_length=32)),
                ('kh', models.CharField(max_length=32)),
                ('pscj', models.FloatField(blank=True, null=True)),
                ('kscj', models.FloatField(blank=True, null=True)),
                ('zpcj', models.FloatField(blank=True, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.C')),
            ],
        ),
        migrations.CreateModel(
            name='O',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh', models.CharField(max_length=32)),
                ('sksj', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.C')),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('xh', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('xm', models.CharField(max_length=32)),
                ('xb', models.CharField(max_length=4)),
                ('csrq', models.DateField()),
                ('jg', models.CharField(max_length=32)),
                ('sjhm', models.CharField(max_length=32, unique=True)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.D')),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('gh', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('xm', models.CharField(max_length=32)),
                ('xb', models.CharField(max_length=4)),
                ('csrq', models.DateField()),
                ('xl', models.CharField(max_length=32)),
                ('gz', models.FloatField()),
                ('pf', models.FloatField()),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.D')),
            ],
        ),
        migrations.CreateModel(
            name='TEMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=32)),
                ('km', models.CharField(max_length=32)),
                ('xf', models.IntegerField()),
                ('gh', models.CharField(max_length=32)),
                ('stats', models.CharField(max_length=32)),
                ('yxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.D')),
            ],
        ),
        migrations.AddField(
            model_name='o',
            name='gh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.T'),
        ),
        migrations.AddField(
            model_name='e',
            name='gh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.T'),
        ),
        migrations.AddField(
            model_name='e',
            name='xh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.S'),
        ),
        migrations.AddField(
            model_name='c',
            name='yxh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSystem.D'),
        ),
        migrations.AlterUniqueTogether(
            name='o',
            unique_together={('kh', 'gh', 'sksj')},
        ),
        migrations.AlterUniqueTogether(
            name='e',
            unique_together={('xn', 'xq', 'xh', 'kh', 'gh')},
        ),
        migrations.AlterUniqueTogether(
            name='c',
            unique_together={('xq', 'kh')},
        ),
    ]
