# Generated by Django 2.1 on 2021-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=32)),
            ],
        ),
    ]
