# Generated by Django 2.1 on 2021-02-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s',
            name='jj',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
